import Head from "next/head";
import React from "react";
import Footer from "./Footer";
import Header from "./Header";

const Layout = ({ children, title }) => {
  return (
    <div>
      <Header />
      <Head>
        <title> {title ? title + " - VeganFood" : "VeganFood"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen">{children}</main>
      <Footer />
    </div>
  );
};

export default Layout;
